Updated installer +  better error handling

diff --git a/files/metis-sideload b/files/metis-sideload
--- a/files/metis-sideload
+++ b/files/metis-sideload
@@ -249,19 +249,51 @@ diskPartition(){
 }
 
 installingBase() {
-  sleep 2s
-  clear
-  echo "Installing Base system..."
-  basestrap /mnt base base-devel runit elogind-runit || installationError
-  sleep 2s
+  basestrap /mnt base base-devel runit elogind-runit
+}
+
+baseCompleted() {
+  s=0
+  for ((i=1;i<=5;i++)); do
+    if ! installingBase; then
+      ((s++))
+      if ((s==5)); then
+        echo "Base installation failed..."
+        installationError
+      fi
+        echo "Base installation failed. Retrying..."
+        sleep 2s
+      else {
+        echo "Base installation successful..."
+        sleep 2s
+        break
+      }
+    fi
+  done
 }
 
 installingKernel() {
-  sleep 2s
-  clear
-  echo "Installing Zen Kernel with its headers and firmware..."
-  basestrap /mnt linux-zen linux-firmware linux-zen-headers || installationError
-  sleep 2s
+  basestrap /mnt linux-zen linux-firmware linux-zen-headers
+}
+
+kernelCompleted() {
+  s=0
+  for ((i=1;i<=5;i++)); do
+    if ! installingKernel; then
+      ((s++))
+      if ((s==5)); then
+        echo "Kernel installation failed..."
+        installationError
+      fi
+        echo "Kernel installation failed. Retrying..."
+        sleep 2s
+      else {
+        echo "Kernel installation successful..."
+        sleep 2s
+        break
+      }
+    fi
+  done
 }
 
 generatingFstab() {
@@ -301,8 +333,8 @@ settingFont
 checkingConnection
 updateMirrors
 diskPartition
-installingBase
-installingKernel
+baseCompleted
+kernelCompleted
 generatingFstab
 copyingConfig
 firstphaseCompleted
