Update metis-sideload
Separate long lines to improve code cleanliness and readability

diff --git a/files/metis-sideload b/files/metis-sideload
--- a/files/metis-sideload
+++ b/files/metis-sideload
@@ -3,7 +3,10 @@
 networkError() {
   sleep 2s
   clear
-  echo -e "Couldnot connect to the internet.\nCheck your Internet Connection and please try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
+  echo -e "Couldnot connect to the internet.\n"
+  echo -e "Check your Internet Connection and please try again.\n"
+  echo -e "Exitting...\n"
+  echo -e "Report any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   sleep 2s
   exit 1
 }
@@ -11,7 +14,11 @@ networkError() {
 failed() {
   sleep 2s
   clear
-  echo -e "Something went wrong.\nThe command could not be executed correctly!\nPlease try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
+  echo -e "Something went wrong.\n"
+  echo -e "The command could not be executed correctly!\n"
+  echo -e "Please try again.\n"
+  echo -e "Exitting...\n"
+  echo -e "Report any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   sleep 2s
   exit 1
 }
@@ -19,7 +26,11 @@ failed() {
 installationError() {
   sleep 2s
   clear
-  echo -e "Something went wrong.\nAll the packages couldn't be installed correctly!\nPlease try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
+  echo -e "Something went wrong.\n"
+  echo -e "All the packages couldn't be installed correctly!\n"
+  echo -e "Please try again.\n"
+  echo -e "Exitting...\n"
+  echo -e "Report any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   sleep 2s
   exit 1
 }
@@ -29,7 +40,10 @@ configError() {
   clear
   echo "Checking configs in new system..."
   if ! ls /mnt/config  &> /dev/null; then 
-    echo -e "Reuired config files couldn't be copied to new system. Installation failed!\nAborting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
+    echo -e "Reuired config files couldn't be copied to new system."
+    echo -e "Installation failed!\n"
+    echo -e "Aborting...\n"
+    echo -e "Report any problem, bug, and errors to https://github.com/metis-os/reports/issues"
     exit 1
   else
     ls /mnt/config
@@ -41,17 +55,24 @@ configError() {
 ignoreableErrors() {
   sleep 2s
   clear
-  echo -e "Something went wrong.\nThe command was not executed correctly!\nThe error can be negleted as it doesn't affect our installation.\nContinuing the installation...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
+  echo -e "Something went wrong.\n"
+  echo -e "The command was not executed correctly!\n"
+  echo -e "The error can be negleted as it doesn't affect our installation.\n"
+  echo -e "Continuing the installation...\n"
+  echo -e "Report any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   sleep 3s
 }
 
 updateMirrors() {
   sleep 2s
   clear
-  if ! which rankmirrors &> /dev/null; then 
-    echo -e "rankmirrors command not found\nCouldn't update the repository mirrorlists\nContinuing without updating mirrors have got chances of installation failure..."
+  if ! which rankmirrors &> /dev/null; then
+    echo -e "rankmirrors command not found\n"
+    echo -e "Couldn't update the repository mirrorlists\n"
+    echo -e "Continuing without updating mirrors have got chances of installation failure..."
   else
-    echo -e "\nUpdating latest and fastest mirrorlists to download packages faster.\nBe patient, this may take some time upto few minutes..."
+    echo -e "\nUpdating latest and fastest mirrorlists to download packages faster.\n"
+    echo -e "Be patient, this may take some time upto few minutes..."
     rankmirrors -n 20 /etc/pacman.d/mirrorlist > /etc/pacman.d/mirrorlist.new
     mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak || ignoreableErrors
     mv /etc/pacman.d/mirrorlist.new /etc/pacman.d/mirrorlist || failed
@@ -72,7 +93,7 @@ checkingConnection() {
 settingFont() {
   sleep 2s
   clear
-  echo "Setting bigger font for better readability..." 
+  echo "Setting bigger font for better readability..."
   sleep 2s
   setfont ter-v22b || ignoreableErrors
 }
@@ -254,7 +275,9 @@ diskPartition(){
   mount /dev/"$rootpartition" /mnt
   if mountpoint /mnt = "/mnt is not a mountpoint"; then
     clear
-    echo -e "$rootpartition is not mounted successfully. Aborting installation!\nInstallation failed..."
+    echo -e "$rootpartition is not mounted successfully."
+    echo -e "Aborting installation!\n"
+    echo -e "Installation failed..."
     exit 1
   else
     echo "Cool $rootpartition mounted at /mnt"
