Edited the sideload

diff --git a/files/metis-sideload b/files/metis-sideload
--- a/files/metis-sideload
+++ b/files/metis-sideload
@@ -1,84 +1,67 @@
 #!/usr/bin/env bash
 
 networkError() {
-  sleep 2s
   clear
-  echo -e "Could not connect to the internet.\nCheck your internet connection and please try again.\nExiting...\nReport any bugs or errors to https://github.com/metis-os/reports/issues"
-  sleep 2s
+  echo -e "Couldnot connect to the internet.\nCheck your Internet Connection and please try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   exit 1
 }
 
 failed() {
-  sleep 2s
   clear
-  echo -e "Something went wrong.\nThe command could not be executed correctly!\nPlease try again.\nExiting...\nReport any bugs or errors to https://github.com/metis-os/reports/issues"
-  sleep 2s
+  echo -e "Something went wrong.\nThe command could not be executed correctly!\nPlease try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   exit 1
 }
 
 installationError() {
-  sleep 2s
   clear
-  echo -e "Something went wrong.\nAll the packages couldn't be installed correctly!\nPlease try again.\nExiting...\nReport any bugs or errors to https://github.com/metis-os/reports/issues"
-  sleep 2s
+  echo -e "Something went wrong.\nAll the packages couldn't be installed correctly!\nPlease try again.\nExitting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
   exit 1
 }
 
 configError() {
-  sleep 2s
   clear
   echo "Checking configs in new system..."
-  if ! ls /mnt/config  &> /dev/null; then
-    echo -e "Required config files couldn't be copied to new system. Installation failed!\nAborting...\nReport any bugs or errors to https://github.com/metis-os/reports/issues"
+  if ! ls /mnt/config  &> /dev/null; then 
+    echo -e "Reuired config files couldn't be copied to new system. Installation failed!\nAborting...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
     exit 1
   else
     ls /mnt/config
     echo "All good..."
-    sleep 5s
   fi
 }
 
 ignoreableErrors() {
-  sleep 2s
   clear
-  echo -e "Something went wrong.\nThe command was not executed correctly!\nThe error can be neglected as it doesn't affect our installation.\nContinuing the installation...\nReport any bugs, and errors to https://github.com/metis-os/reports/issues"
-  sleep 3s
+  echo -e "Something went wrong.\nThe command was not executed correctly!\nThe error can be negleted as it doesn't affect our installation.\nContinuing the installation...\nReport any problem, bug, and errors to https://github.com/metis-os/reports/issues"
 }
 
 updateMirrors() {
-  sleep 2s
   clear
-  if ! which rankmirrors &> /dev/null; then
-    echo -e "rankmirrors isn't installed.\nCouldn't update the repository mirrorlists\nContinuing without updating mirrors will increase the chances of installation failure..."
+  if ! which rankmirrors &> /dev/null; then 
+    echo -e "rankmirrors command not found\nCouldn't update the repository mirrorlists\nContinuing without updating mirrors have got chances of installation failure..."
   else
-    echo -e "\nUpdating latest and fastest mirrorlists to download packages.\nBe patient, this may take some time..."
-    rankmirrors -n 20 /etc/pacman.d/mirrorlist > /etc/pacman.d/mirrorlist.new
-    mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak || ignoreableErrors
-    mv /etc/pacman.d/mirrorlist.new /etc/pacman.d/mirrorlist || failed
+    echo -e "\nUpdating latest and fastest mirrorlists to download packages faster.\nBe patient, this may take some time upto few minutes..."
+#    rankmirrors -n 20 /etc/pacman.d/mirrorlist > /etc/pacman.d/mirrorlist.new
+#   mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak || ignoreableErrors
+#    mv /etc/pacman.d/mirrorlist.new /etc/pacman.d/mirrorlist || failed
     echo "Mirrorlists updated..."
-    sleep 2s
   fi
 }
 
 checkingConnection() {
-  sleep 2s
   clear
   echo "Checking internet connection..."
-  ping -c 3 metislinux.org || networkError
-  echo  "Cool! Internet connection available. Getting ready for installation..."
-  sleep 3s
+  ping -q  -c1 metislinux.org || networkError
+  echo  "Cool! Internet Connection Available. Getting ready for installation..."
 }
 
 settingFont() {
-  sleep 2s
   clear
-  echo "Setting bigger font for better readability..."
-  sleep 2s
+  echo "Setting bigger font for better readability..." 
   setfont ter-v22b || ignoreableErrors
 }
 
 displayArt(){
-  sleep 2s
   clear
   echo -ne "
   __________________________________________________________________________________________________________
@@ -88,18 +71,20 @@ displayArt(){
   |                       +-+-+-+-+-+        +-+-+-+-+-+        +-+-+-+-+-+-+-+-+-+                         |
   |                                                                                                         |
   |---------------------------------------------------------------------------------------------------------|
-  |                                 Official CLI installer for Metis Linux                                  |
+  |                                 Official Cli installer for metis linux.                                 |
   |---------------------------------------------------------------------------------------------------------|
   |                                 Install Metis Linux in few clicks                                       |
   |               Check: https://github.com/metis-os for details or visit https://metislinux.org            |
   |---------------------------------------------------------------------------------------------------------|
   |_________________________________________________________________________________________________________|
   "
+  echo "Press any key to start the installation process"
+  read -r nothing
 }
 
 selectDrive() {
   lsblk
-  echo "Enter the drive to install metis linux on."
+  echo "Enter the drive to install metis linux on it."
   echo "Enter Drive (eg. sda or vda or nvme0n1): "
   read -r drive
 }
@@ -108,7 +93,7 @@ checkDrive() {
   while ! lsblk | grep "$drive"  &> /dev/null
   do
     clear
-    echo -e "$drive was not found. Check your available disks and try again..."
+    echo -e "$drive is not found. Check your available disks and try again..."
     selectDrive
   done
 }
@@ -123,7 +108,7 @@ checkRoot() {
   while ! lsblk | grep "$rootpartition"  &> /dev/null
   do
     clear
-    echo -e "$rootpartition was not found. Check your available partitions and try again..."
+    echo -e "$rootpartition is not found. Check your available partitions and try again..."
     selectRoot
   done
 }
@@ -138,7 +123,7 @@ checkHome() {
   while ! lsblk | grep "$homepartition"  &> /dev/null
   do
     clear
-    echo -e "$homepartition partition was not found. Check your available partitions and try again..."
+    echo -e "$homepartition partition is not found. Check your available partitions and try again..."
     selectHome
   done
 }
@@ -153,28 +138,25 @@ checkSwap() {
   while ! lsblk | grep "$swappartition"  &> /dev/null
   do
     clear
-    echo -e "$swappartition partition was not found. Check your available partitions and try again..."
+    echo -e "$swappartition partition is not found. Check your available partitions and try again..."
     selectSwap
   done
 }
 
 diskPartition(){
-  sleep 2s
   clear
   echo -ne "
   ------------------------------------------------------------------------
           THIS WILL FORMAT AND DELETE ALL DATA ON THE DISK
         Please make sure you know what you are doing because
-      after formatting your disk there is no way to get data back
+      after formating your disk there is no way to get data back
   ------------------------------------------------------------------------
   "
-  sleep 5s
   selectDrive
   checkDrive
-  sleep 2s
   clear
   lsblk
-  echo "Choose a disk utility tool to partition your drive! [Default=cfdisk]: "
+  echo "Choose a familier disk utility tool to partition your drive! [Default=cfdisk]: "
   echo " 1. fdisk"
   echo " 2. cfdisk"
   echo " 3. gdisk"
@@ -201,23 +183,21 @@ diskPartition(){
   esac
   echo "$partitionutility is the selected disk utility tool for partition."
   echo "Getting ready for creating partitions!"
-  sleep 2s
   clear
-  echo "boot partition is mandatory for UEFI systems. Skip it for legacy systems"
+  echo "boot partition is mandatory for uefi systems. Skip it for legacy systems"
   echo "root partition is mandatory."
   echo "home and swap partitions are optional but recommended!"
   echo "Also, you can create a separate partition for timeshift backup (optional)!"
   echo "Getting ready in 15 seconds"
-  sleep 15s
   "$partitionutility" /dev/"$drive"
   clear
   lsblk
   echo " 1. ext4"
   echo " 2. xfs"
-  echo " 3. btrfs (only for UEFI systems. legacy systems do not support btrfs)"
+  echo " 3. btrfs (only for uefi systems. leagacy system doesnot support btrfs)"
   echo " 4. f2fs"
-  echo " Boot partition will be formatted later in fat32 file system (for UEFI systems only)."
-  echo "Choose your Linux file system type for formatting drives [default=ext4]: "
+  echo " Boot partition will be formatted later in fat32 file system (for uefi systems only)."
+  echo "Choose your linux file system type for formatting drives [default=ext4]: "
   read -r filesystemtype
 
   case "$filesystemtype" in
@@ -241,7 +221,7 @@ diskPartition(){
     filesystemtype="f2fs"
     ;;
     *)
-    echo "Unknown or unsupported file system. Default = ext4."
+    echo "Unknown or unsupported Filesystem. Default = ext4."
     filesystemtype="ext4"
     ;;
   esac
@@ -258,12 +238,11 @@ diskPartition(){
     exit 1
   else
     echo "Cool $rootpartition mounted at /mnt"
-    sleep 2s
   fi
 
   clear
   lsblk
-  echo "Did you create a separate home partition? [y/n]: "
+  echo "Did you create a separate home partition? [y/n]: " 
   read -r answerhome
   case "$answerhome" in
     y | Y | yes | Yes | YES)
@@ -278,7 +257,6 @@ diskPartition(){
       exit 1
     else
       echo "Cool $homepartition mounted at /mnt/home"
-      sleep 2s
     fi
     ;;
     *)
@@ -301,7 +279,6 @@ diskPartition(){
     ;;
   esac
   lsblk
-  sleep 2s
 }
 
 installingBase() {
@@ -318,10 +295,8 @@ baseCompleted() {
         installationError
       fi
         echo "Base installation failed. Retrying..."
-        sleep 3s
       else {
         echo "Base installation successful..."
-        sleep 2s
         break
       }
     fi
@@ -342,10 +317,8 @@ kernelCompleted() {
         installationError
       fi
         echo "Kernel installation failed. Retrying..."
-        sleep 3s
       else {
         echo "Kernel installation successful..."
-        sleep 2s
         break
       }
     fi
@@ -353,17 +326,14 @@ kernelCompleted() {
 }
 
 generatingFstab() {
-  sleep 2s
   clear
   echo "generating fstab file"
   fstabgen -U /mnt > /mnt/etc/fstab || failed
-  echo "Checking fstab contents..."
+  echo "Checking Fstab Contents..."
   cat /mnt/etc/fstab
-  sleep 3s
 }
 
 copyingConfig() {
-  sleep 2s
   clear
   echo "Copying config files to new system..."
   cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist || ignoreableErrors
@@ -375,7 +345,6 @@ copyingConfig() {
 }
 
 firstphaseCompleted(){
-  sleep 2s
   clear
   echo "First Phase Completed!"
   echo "Entering into Second Phase of Installation..."
